config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: %i[index show]
  resources :events do
    resource :enrollments, only: %i[create destroy], module: :events
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: User.name, foreign_key: :user_id, inverse_of: :events
  has_many :enrollments, dependent: :destroy
  has_many :attendees, through: :enrollments, source: :user

  scope :past, -> { where("date < ?", DateTime.now) }
  scope :future, -> { where("date > ?", DateTime.now) }
end

app/controllers/events/enrollments_controller.rb
class Events::EnrollmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def create
    enrollment = current_user.enrollments.new(event: @event)

    if enrollment.save
      flash[:notice] = "You are now attending this event!"
      redirect_to @event, status: :see_other
    else
      flash[:alert] = "Some error!"
      redirect_to @event, status: :unprocessable_entity
    end
  end

  def destroy
    enrollment = current_user.enrollments.find_by(event: @event)

    if enrollment.destroy
      flash[:notice] = "You are no longer attending this event!"
      redirect_to @event, status: :see_other
    else
      flash[:alert] = "Some error!"
      redirect_to @event, status: :unprocessable_entity
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_event, except: %i[index show new create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.includes(:attendees).find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = "Event '#{@event.name}' created!"
      redirect_to @event, status: :see_other
    else
      flash[:alert] = "Event '#{@event.name}' has errors!"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Event '#{@event.name}' updated!"
      redirect_to @event, status: :see_other
    else
      flash[:alert] = "Event '#{@event.name}' has errors!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "Event '#{@event.name}' destroyed!"
      redirect_to @event, status: :see_other
    else
      flash[:alert] = "Event '#{@event.name}' has errors!"
      redirect_to @event, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: true %><br><br>

  <%= form.label :date %>
  <%= form.datetime_field :date %><br><br>

  <%= form.label :location %>
  <%= form.text_field :location %><br><br>

  <%= form.label :description %>
  <%= form.text_area :description %><br><br>

  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1>Events:</h1>

<ul>
  <% @events.each do |event| %>
    <li><%= link_to event.name, event %></li>
  <% end %>
</ul>

<% if user_signed_in? %>
  <%= link_to 'Create new event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1><%= @event.name %> (<%= @event.date %>)</h1>
<h2><%= @event.location %></h2>
<h2><%= @event.description %></h2>

<% if user_signed_in? %>
  <% if Enrollment.exists?(event: @event, user: current_user) %>
    <%= button_to "Destroy enrollment", event_enrollments_path(@event), method: :delete %>
  <% else %>
    <%= button_to "Create enrollment", event_enrollments_path(@event) %>
  <% end %>

  <% if @event.creator == current_user %>
    <%= link_to "Edit Event", edit_event_path(@event) %>
    <%= button_to "Destroy Event", event_path(@event), method: :delete %>
  <% end %>
<% end %>

<h1>List of attendees:</h1>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= link_to attendee.email, attendee %></li>
  <% end %>
</ul>